version: '3'  
services:
  ainterview-processor:
    image: ainterview-processor-image
    container_name: ainterview-processor-container
    build:
      context: ./
      args:
        - INSTANCE=processor
    ports:
      - "7002:5000"
    networks:
      - ainterview_network
networks:
  ainterview_network:
     external: true
